-- 오너클랜 상품 변경 이력 정보를 저장하기 위한 테이블 스키마

CREATE TABLE IF NOT EXISTS public.ownerclan_item_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "itemKey" TEXT NOT NULL,
    kind TEXT,
    title TEXT,
    "valueBefore" TEXT,
    "valueAfter" TEXT,
    "createdAt" TIMESTAMPTZ,
    "lastSyncedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ownerclan_item_histories_itemKey ON public.ownerclan_item_histories("itemKey");
CREATE INDEX IF NOT EXISTS idx_ownerclan_item_histories_createdAt ON public.ownerclan_item_histories("createdAt");

COMMENT ON TABLE public.ownerclan_item_histories IS '오너클랜 API를 통해 수집된 상품 변경 이력';
COMMENT ON COLUMN public.ownerclan_item_histories.id IS '레코드 고유 ID';
COMMENT ON COLUMN public.ownerclan_item_histories."itemKey" IS '상품 고유 키';
COMMENT ON COLUMN public.ownerclan_item_histories.kind IS '변경 이력 종류 (예: soldout)';
COMMENT ON COLUMN public.ownerclan_item_histories.title IS '변경 내용 타이틀';
COMMENT ON COLUMN public.ownerclan_item_histories."valueBefore" IS '변경 전 값';
COMMENT ON COLUMN public.ownerclan_item_histories."valueAfter" IS '변경 후 값';
COMMENT ON COLUMN public.ownerclan_item_histories."createdAt" IS '변경 발생 시각';
COMMENT ON COLUMN public.ownerclan_item_histories."lastSyncedAt" IS 'Supabase와 마지막으로 동기화된 시각';
