#!/usr/bin/env python3
"""
쿠팡 파트너스 API - 상품 관리 패키지
"""

# 메인 클라이언트 클래스 (리팩토링된 버전)
from .client import ProductClient

# 분리된 클라이언트들 (고급 사용자용)
from .product_management_client import ProductManagementClient
from .product_query_client import ProductQueryClient
from .vendor_item_client import VendorItemClient
from .auto_generated_option_client import AutoGeneratedOptionClient

# 공통 유틸리티
from .utils import (
    setup_project_path, format_api_response, handle_api_success, handle_api_error,
    handle_exception_error, print_test_header, print_test_section,
    print_api_request_info, print_api_result, get_env_or_default,
    validate_environment_variables
)

# 데이터 모델들
from .models import (
    ProductImage,
    ProductCertification,
    ProductNotice,
    ProductAttribute,
    ProductContentDetail,
    ProductContent,
    ProductRequiredDocument,
    ProductItem,
    ProductRequest,
    ProductSearchParams,
    ProductPartialUpdateRequest,
    ProductStatusHistoryParams
)

# 상수들
from .constants import (
    DELIVERY_METHODS,
    DELIVERY_CHARGE_TYPES,
    DELIVERY_COMPANIES,
    PRODUCT_STATUS,
    IMAGE_TYPES,
    CONTENT_TYPES,
    CERTIFICATION_TYPES
)

# 검증 함수들
from .validators import (
    validate_product_request,
    validate_product_update_request,
    validate_product_partial_update_request,
    validate_product_search_params,
    validate_time_frame_params,
    validate_product_status_history_params,
    validate_external_vendor_sku_code,
    validate_vendor_item_id,
    validate_quantity,
    validate_price,
    validate_original_price,
    validate_vendor_id,
    validate_image_requirements,
    validate_search_tags
)

__version__ = "1.0.0"
__author__ = "Coupang Product API Client"

# 편의성을 위한 별칭들
Client = ProductClient
SearchParams = ProductSearchParams
PartialUpdateRequest = ProductPartialUpdateRequest
StatusHistoryParams = ProductStatusHistoryParams

# 분리된 클라이언트 별칭들
ProductMgmt = ProductManagementClient
ProductQuery = ProductQueryClient
VendorItem = VendorItemClient
AutoGenOption = AutoGeneratedOptionClient

# 편의 함수 추가
def create_product_client(access_key=None, secret_key=None, vendor_id=None):
    """
    상품 클라이언트 생성 편의 함수
    
    Args:
        access_key: 쿠팡 액세스 키 (None이면 .env에서 읽음)
        secret_key: 쿠팡 시크릿 키 (None이면 .env에서 읽음)
        vendor_id: 쿠팡 벤더 ID (None이면 .env에서 읽음)
        
    Returns:
        ProductClient: 초기화된 상품 클라이언트
    """
    return ProductClient(access_key, secret_key, vendor_id)

# 패키지 정보
__all__ = [
    # 편의 함수
    'create_product_client',
    # 메인 클라이언트
    'ProductClient', 'Client',
    
    # 분리된 클라이언트들
    'ProductManagementClient', 'ProductMgmt',
    'ProductQueryClient', 'ProductQuery', 
    'VendorItemClient', 'VendorItem',
    'AutoGeneratedOptionClient', 'AutoGenOption',
    
    # 공통 유틸리티
    'setup_project_path', 'format_api_response', 'handle_api_success', 'handle_api_error',
    'handle_exception_error', 'print_test_header', 'print_test_section',
    'print_api_request_info', 'print_api_result', 'get_env_or_default',
    'validate_environment_variables',
    
    # 모델 클래스들
    'ProductImage',
    'ProductCertification', 
    'ProductNotice',
    'ProductAttribute',
    'ProductContentDetail',
    'ProductContent',
    'ProductRequiredDocument',
    'ProductItem',
    'ProductRequest',
    'ProductSearchParams', 'SearchParams',
    'ProductPartialUpdateRequest', 'PartialUpdateRequest',
    'ProductStatusHistoryParams', 'StatusHistoryParams',
    
    # 상수들
    'DELIVERY_METHODS',
    'DELIVERY_CHARGE_TYPES', 
    'DELIVERY_COMPANIES',
    'PRODUCT_STATUS',
    'IMAGE_TYPES',
    'CONTENT_TYPES',
    'CERTIFICATION_TYPES',
    
    # 검증 함수들
    'validate_product_request',
    'validate_product_update_request',
    'validate_product_partial_update_request',
    'validate_product_search_params',
    'validate_time_frame_params',
    'validate_product_status_history_params',
    'validate_external_vendor_sku_code',
    'validate_vendor_item_id',
    'validate_quantity',
    'validate_price',
    'validate_original_price',
    'validate_vendor_id',
    'validate_image_requirements',
    'validate_search_tags'
]