-- Migration: create tables for multi-market, multi-account architecture
-- Enable uuid-ossp extension for uuid generation if not already
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. markets table
CREATE TABLE IF NOT EXISTS markets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT UNIQUE NOT NULL, -- e.g., COUPANG, NAVER
    name          TEXT NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE markets IS '마켓 종류 정의 (Coupang, Naver 등)';

-- 2. accounts table (vendor / seller account per market)
CREATE TABLE IF NOT EXISTS accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id     BIGINT NOT NULL REFERENCES markets(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,                       -- 계정 표시명
    credentials   JSONB,                              -- 암호화된 자격 정보 / 토큰
    active        BOOLEAN DEFAULT TRUE,
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now(),
    UNIQUE (market_id, name)
);

COMMENT ON TABLE accounts IS '마켓별 개별 판매자 계정 정보';

-- 3. orders (통합 주문)
CREATE TABLE IF NOT EXISTS orders (
    id                 UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    market_order_id    TEXT,            -- 마켓 주문번호
    shipment_box_id    TEXT,            -- (Coupang) 배송박스 ID 등
    market_id          BIGINT NOT NULL REFERENCES markets(id),
    account_id         BIGINT NOT NULL REFERENCES accounts(id),
    status             TEXT,            -- NEW/RECEIVED/SHIPPED/ERROR 등

    ordered_at         TIMESTAMPTZ,
    paid_at            TIMESTAMPTZ,
    invoice_number     TEXT,
    delivered_date     TIMESTAMPTZ,

    raw_data           JSONB,
    created_at         TIMESTAMPTZ DEFAULT now(),
    updated_at         TIMESTAMPTZ DEFAULT now(),

    UNIQUE (market_order_id, account_id),
    UNIQUE (shipment_box_id, account_id)
);

COMMENT ON TABLE orders IS '통합 주문 테이블 (모든 마켓)';

-- 4. order_items
CREATE TABLE IF NOT EXISTS order_items (
    id                TEXT PRIMARY KEY,   -- 마켓별 unique item id (orderItemId 등)
    order_id          UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_mapping_id BIGINT,
    quantity          INT,
    price             NUMERIC,
    raw_item_data     JSONB,
    created_at        TIMESTAMPTZ DEFAULT now(),
    updated_at        TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE order_items IS '주문별 상품 항목';

-- 5. ownerclan_orders (발주 결과)
CREATE TABLE IF NOT EXISTS ownerclan_orders (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    ownerclan_key      TEXT UNIQUE,         -- ownerclan order key
    ownerclan_order_id TEXT,               -- numeric id if 제공됨
    tracking_number    TEXT,
    status             TEXT,               -- ORDERED/SHIPPED/ERROR 등
    raw_response       JSONB,
    created_at         TIMESTAMPTZ DEFAULT now(),
    updated_at         TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE ownerclan_orders IS 'Ownerclan 발주 및 송장 정보';

-- 6. product_mappings (SKU ↔ Ownerclan itemKey)
CREATE TABLE IF NOT EXISTS product_mappings (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id          BIGINT NOT NULL REFERENCES markets(id) ON DELETE CASCADE,
    account_id         BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    market_sku         TEXT NOT NULL,
    ownerclan_item_key TEXT NOT NULL,
    options            JSONB,
    created_at         TIMESTAMPTZ DEFAULT now(),
    updated_at         TIMESTAMPTZ DEFAULT now(),
    UNIQUE (market_id, account_id, market_sku)
);

COMMENT ON TABLE product_mappings IS '마켓 SKU와 Ownerclan itemKey 매핑';

-- 7. automation_logs
CREATE TABLE IF NOT EXISTS automation_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level       TEXT NOT NULL,          -- INFO/WARN/ERROR
    message     TEXT,
    payload     JSONB,
    created_at  TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE automation_logs IS '자동화 프로세스 이벤트·에러 로그';
